import raw from "/tmp/opencode/raw-pac-results.json";

export type PacSpendingItem = {
  pacName: string
  position: "FOR" | "AGAINST"
  amount: number
  currency: string
  description: string
  sourceUrl: string
  sourceName: string
}

export type PacCandidate = {
  name: string
  pacSpending: PacSpendingItem[]
}

export type PacRace = {
  raceId: string
  raceTitle: string
  subtitle?: string
  party?: string
  candidates: PacCandidate[]
}

function sum(items: PacSpendingItem[], position: "FOR" | "AGAINST"): number {
  return items
    .filter((i) => i.position === position)
    .reduce((acc, i) => acc + (Number(i.amount) || 0), 0);
}

function formatCurrency(n: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(n);
}

const races: PacRace[] = raw as PacRace[];

// Generate typed data module
const dataModule = `// Auto-generated by scripts/generate-pac-report.ts
// DO NOT EDIT MANUALLY

export type PacSpendingItem = {
  pacName: string
  position: "FOR" | "AGAINST"
  amount: number
  currency: string
  description: string
  sourceUrl: string
  sourceName: string
}

export type PacCandidate = {
  name: string
  pacSpending: PacSpendingItem[]
}

export type PacRace = {
  raceId: string
  raceTitle: string
  subtitle?: string
  party?: string
  candidates: PacCandidate[]
}

export const pacSpendingRaces: PacRace[] = ${JSON.stringify(races, null, 2)}
`;

await Bun.write("src/data/pac-spending.ts", dataModule);

// Generate markdown report
let md = `# Oklahoma 2026 Primary PAC Spending Report\n\n`;
md += `**Election:** June 16, 2026 Primary\n\n`;
md += `**Coverage:** Statewide and Congressional races. Legislative, local, and judicial races were excluded because PAC spending in those primaries is typically minimal or unreported.\n\n`;
md += `**Sources:** Federal Election Commission (FEC) and Oklahoma Ethics Commission Guardian system.\n\n`;
md += `---\n\n`;

for (const race of races) {
  const raceLabel = [race.raceTitle, race.subtitle, race.party ? `(${race.party})` : ""]
    .filter(Boolean)
    .join(" ");
  md += `## ${raceLabel}\n\n`;

  for (const candidate of race.candidates) {
    const forTotal = sum(candidate.pacSpending, "FOR");
    const againstTotal = sum(candidate.pacSpending, "AGAINST");
    md += `### ${candidate.name}\n\n`;
    md += `- **Total FOR:** ${formatCurrency(forTotal)}\n`;
    md += `- **Total AGAINST:** ${formatCurrency(againstTotal)}\n\n`;

    if (candidate.pacSpending.length === 0) {
      md += `_No reported PAC spending found._\n\n`;
      continue;
    }

    md += `| PAC | Position | Amount | Description | Source |\n`;
    md += `|-----|----------|--------|-------------|--------|\n`;
    for (const item of candidate.pacSpending) {
      const sourceLink = `[${item.sourceName}](${item.sourceUrl})`;
      const desc = item.description.replace(/\|/g, "\\|").replace(/\n/g, " ");
      const pac = item.pacName.replace(/\|/g, "\\|");
      md += `| ${pac} | ${item.position} | ${formatCurrency(item.amount)} | ${desc} | ${sourceLink} |\n`;
    }
    md += `\n`;
  }
}

md += `---\n\n`;
md += `*Report generated on ${new Date().toISOString().split("T")[0]}.*\n`;

await Bun.write("PAC_SPENDING_REPORT.md", md);

console.log("Generated src/data/pac-spending.ts");
console.log("Generated PAC_SPENDING_REPORT.md");

// Print summary stats
const totalCandidates = races.reduce((acc, r) => acc + r.candidates.length, 0);
const candidatesWithSpending = races.reduce(
  (acc, r) => acc + r.candidates.filter((c) => c.pacSpending.length > 0).length,
  0
);
const totalFor = races.reduce(
  (acc, r) =>
    acc + r.candidates.reduce((cacc, c) => cacc + sum(c.pacSpending, "FOR"), 0),
  0
);
const totalAgainst = races.reduce(
  (acc, r) =>
    acc + r.candidates.reduce((cacc, c) => cacc + sum(c.pacSpending, "AGAINST"), 0),
  0
);

console.log(`\nSummary:`);
console.log(`  Races: ${races.length}`);
console.log(`  Candidates: ${totalCandidates}`);
console.log(`  Candidates with PAC spending: ${candidatesWithSpending}`);
console.log(`  Total FOR: ${formatCurrency(totalFor)}`);
console.log(`  Total AGAINST: ${formatCurrency(totalAgainst)}`);
console.log(`  Grand total: ${formatCurrency(totalFor + totalAgainst)}`);
