/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PacSpendingRouteImport } from './routes/pac-spending'
import { Route as IndexRouteImport } from './routes/index'

const PacSpendingRoute = PacSpendingRouteImport.update({
  id: '/pac-spending',
  path: '/pac-spending',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pac-spending': typeof PacSpendingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pac-spending': typeof PacSpendingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pac-spending': typeof PacSpendingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pac-spending'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pac-spending'
  id: '__root__' | '/' | '/pac-spending'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PacSpendingRoute: typeof PacSpendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pac-spending': {
      id: '/pac-spending'
      path: '/pac-spending'
      fullPath: '/pac-spending'
      preLoaderRoute: typeof PacSpendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PacSpendingRoute: PacSpendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
