// Auto-generated by scripts/generate-pac-report.ts
// DO NOT EDIT MANUALLY

export type PacSpendingItem = {
  pacName: string
  position: "FOR" | "AGAINST"
  amount: number
  currency: string
  description: string
  sourceUrl: string
  sourceName: string
}

export type PacCandidate = {
  name: string
  pacSpending: PacSpendingItem[]
}

export type PacRace = {
  raceId: string
  raceTitle: string
  subtitle?: string
  party?: string
  candidates: PacCandidate[]
}

export const pacSpendingRaces: PacRace[] = [
  {
    "raceId": "for-governor-republican",
    "raceTitle": "FOR GOVERNOR",
    "party": "REPUBLICAN",
    "candidates": [
      {
        "name": "CALUP ANTHONY TAYLOR",
        "pacSpending": []
      },
      {
        "name": "JENNIFER DOMENICO",
        "pacSpending": []
      },
      {
        "name": "GENTNER DRUMMOND",
        "pacSpending": [
          {
            "pacName": "Make Oklahoma Great Again PAC",
            "position": "FOR",
            "amount": 3000000,
            "currency": "USD",
            "description": "Independent expenditure ads supporting Gentner Drummond (PAC's reported total also included opposition to Mike Mazzei)",
            "sourceUrl": "https://oklahomawatch.org/2026/06/15/republican-primaries-for-governor-attorney-general-drive-record-outside-spending/",
            "sourceName": "Oklahoma Watch"
          },
          {
            "pacName": "School Freedom Fund Oklahoma",
            "position": "AGAINST",
            "amount": 3100000,
            "currency": "USD",
            "description": "Attack ads targeting Drummond over his opposition to a religious charter school; Drummond was the only Oklahoma candidate targeted by this Club for Growth-affiliated group",
            "sourceUrl": "https://oklahomawatch.org/2026/06/15/republican-primaries-for-governor-attorney-general-drive-record-outside-spending/",
            "sourceName": "Oklahoma Watch"
          },
          {
            "pacName": "Oklahoma Conservative Coalition",
            "position": "AGAINST",
            "amount": 2000000,
            "currency": "USD",
            "description": "Part of the super PAC's nearly $2 million campaign supporting Charles McCall and opposing Drummond, Keating and Mazzei",
            "sourceUrl": "https://witness.usatoday.com/story/news/politics/2026/05/26/oklahoma-elections-2026-pacs-are-spending-millions-in-gop-governors-race/90199853007/",
            "sourceName": "USA TODAY / The Oklahoman"
          }
        ]
      },
      {
        "name": "KENNETH STURGELL",
        "pacSpending": []
      },
      {
        "name": "CHIP KEATING",
        "pacSpending": [
          {
            "pacName": "Oklahoma Conservative Coalition",
            "position": "AGAINST",
            "amount": 2000000,
            "currency": "USD",
            "description": "Part of the super PAC's nearly $2 million campaign supporting Charles McCall and opposing Drummond, Keating and Mazzei",
            "sourceUrl": "https://witness.usatoday.com/story/news/politics/2026/05/26/oklahoma-elections-2026-pacs-are-spending-millions-in-gop-governors-race/90199853007/",
            "sourceName": "USA TODAY / The Oklahoman"
          },
          {
            "pacName": "Faith and Freedom Forward PAC",
            "position": "AGAINST",
            "amount": 1500000,
            "currency": "USD",
            "description": "Part of $1.5 million in combined opposition spending against Keating from Oklahoma Conservative Coalition and Faith and Freedom Forward PAC",
            "sourceUrl": "https://oklahomawatch.org/2026/06/15/republican-primaries-for-governor-attorney-general-drive-record-outside-spending/",
            "sourceName": "Oklahoma Watch"
          }
        ]
      },
      {
        "name": "MIKE MAZZEI",
        "pacSpending": [
          {
            "pacName": "Make Oklahoma Great Again PAC",
            "position": "AGAINST",
            "amount": 3000000,
            "currency": "USD",
            "description": "Part of the PAC's $3 million campaign supporting Drummond and opposing Mazzei",
            "sourceUrl": "https://oklahomawatch.org/2026/06/15/republican-primaries-for-governor-attorney-general-drive-record-outside-spending/",
            "sourceName": "Oklahoma Watch"
          },
          {
            "pacName": "Oklahoma Conservative Coalition",
            "position": "AGAINST",
            "amount": 2000000,
            "currency": "USD",
            "description": "Part of the super PAC's nearly $2 million campaign supporting Charles McCall and opposing Drummond, Keating and Mazzei",
            "sourceUrl": "https://witness.usatoday.com/story/news/politics/2026/05/26/oklahoma-elections-2026-pacs-are-spending-millions-in-gop-governors-race/90199853007/",
            "sourceName": "USA TODAY / The Oklahoman"
          }
        ]
      },
      {
        "name": "JAKE A. MERRICK",
        "pacSpending": []
      },
      {
        "name": "CHARLES MCCALL",
        "pacSpending": [
          {
            "pacName": "Oklahoma Conservative Coalition",
            "position": "FOR",
            "amount": 2000000,
            "currency": "USD",
            "description": "Super PAC ads supporting McCall; the PAC also opposed Drummond, Keating and Mazzei",
            "sourceUrl": "https://witness.usatoday.com/story/news/politics/2026/05/26/oklahoma-elections-2026-pacs-are-spending-millions-in-gop-governors-race/90199853007/",
            "sourceName": "USA TODAY / The Oklahoman"
          },
          {
            "pacName": "Make Oklahoma Great Again PAC",
            "position": "AGAINST",
            "amount": 875000,
            "currency": "USD",
            "description": "AI-generated deepfake attack ads opposing McCall (part of $875,000+ campaign also supporting Drummond and opposing Mazzei)",
            "sourceUrl": "https://witness.usatoday.com/story/news/politics/2026/05/26/oklahoma-elections-2026-pacs-are-spending-millions-in-gop-governors-race/90199853007/",
            "sourceName": "USA TODAY / The Oklahoman"
          }
        ]
      },
      {
        "name": "LEISA MITCHELL HAYNES",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-governor-democrat",
    "raceTitle": "FOR GOVERNOR",
    "party": "DEMOCRAT",
    "candidates": [
      {
        "name": "CONNIE JOHNSON",
        "pacSpending": []
      },
      {
        "name": "ARYA",
        "pacSpending": []
      },
      {
        "name": "CYNDI MUNSON",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-united-states-senator-republican",
    "raceTitle": "FOR UNITED STATES SENATOR",
    "party": "REPUBLICAN",
    "candidates": [
      {
        "name": "NICK HANKINS",
        "pacSpending": []
      },
      {
        "name": "GARY TY ENGLAND",
        "pacSpending": []
      },
      {
        "name": "KEVIN HERN",
        "pacSpending": [
          {
            "pacName": "DEFENDING OUR VALUES PAC",
            "position": "FOR",
            "amount": 808341.4,
            "currency": "USD",
            "description": "TV advertising production and media buy supporting Kevin Hern",
            "sourceUrl": "https://www.fec.gov/data/independent-expenditures/?data_type=processed&committee_id=C00928390&candidate_id=S6OK04247&cycle=2026&support_oppose=S",
            "sourceName": "FEC"
          },
          {
            "pacName": "DEFEND AMERICAN JOBS",
            "position": "FOR",
            "amount": 735613.2,
            "currency": "USD",
            "description": "Media production and media buy supporting Kevin Hern",
            "sourceUrl": "https://www.fec.gov/data/independent-expenditures/?data_type=processed&committee_id=C00836221&candidate_id=S6OK04247&cycle=2026&support_oppose=S",
            "sourceName": "FEC"
          },
          {
            "pacName": "FELLOWSHIP PAC",
            "position": "FOR",
            "amount": 300000,
            "currency": "USD",
            "description": "Advertising supporting Kevin Hern",
            "sourceUrl": "https://www.fec.gov/data/independent-expenditures/?data_type=processed&committee_id=C00915181&candidate_id=S6OK04247&cycle=2026&support_oppose=S",
            "sourceName": "FEC"
          },
          {
            "pacName": "AMERICAN MISSION",
            "position": "FOR",
            "amount": 220616.55,
            "currency": "USD",
            "description": "Media placement, text messages, and media production supporting Kevin Hern",
            "sourceUrl": "https://www.fec.gov/data/independent-expenditures/?data_type=processed&committee_id=C00916692&candidate_id=S6OK04247&cycle=2026&support_oppose=S",
            "sourceName": "FEC"
          },
          {
            "pacName": "SENATE CONSERVATIVES FUND",
            "position": "FOR",
            "amount": 46020.12,
            "currency": "USD",
            "description": "Direct mail, digital marketing, printing, postage, and donation processing supporting Kevin Hern",
            "sourceUrl": "https://www.fec.gov/data/independent-expenditures/?data_type=processed&committee_id=C00448696&candidate_id=S6OK04247&cycle=2026&support_oppose=S",
            "sourceName": "FEC"
          }
        ]
      },
      {
        "name": "SEAN BUCKNER",
        "pacSpending": []
      },
      {
        "name": "BRIAN RAGAIN",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-united-states-senator-democrat",
    "raceTitle": "FOR UNITED STATES SENATOR",
    "party": "DEMOCRAT",
    "candidates": [
      {
        "name": "TROY W. GREEN",
        "pacSpending": []
      },
      {
        "name": "ERVIN STONE YEN",
        "pacSpending": []
      },
      {
        "name": "R.O. JOE CASSITY JR.",
        "pacSpending": []
      },
      {
        "name": "N'KIYLA JASMINE THOMAS",
        "pacSpending": []
      },
      {
        "name": "JIM PRIEST",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-superintendent-of-public-instruction-republican",
    "raceTitle": "FOR SUPERINTENDENT OF PUBLIC INSTRUCTION",
    "party": "REPUBLICAN",
    "candidates": [
      {
        "name": "TONI HASENBECK",
        "pacSpending": [
          {
            "pacName": "Crimson and Cream PAC",
            "position": "FOR",
            "amount": 1000,
            "currency": "USD",
            "description": "PAC contribution to Toni Hasenbeck's candidate committee on 01/27/2026 (reported as PAC expenditure)",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ExpenditureExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission (Guardian System)"
          }
        ]
      },
      {
        "name": "JOHN COX",
        "pacSpending": [
          {
            "pacName": "OKC Retired Firefighters Assoc.",
            "position": "FOR",
            "amount": 1000,
            "currency": "USD",
            "description": "PAC contribution to John Cox's candidate committee on 04/09/2026 (unregistered PAC)",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission (Guardian System)"
          }
        ]
      },
      {
        "name": "ROBERT FRANKLIN",
        "pacSpending": []
      },
      {
        "name": "JAMES TAYLOR",
        "pacSpending": []
      },
      {
        "name": "ADAM PUGH",
        "pacSpending": [
          {
            "pacName": "Delta Dental of Oklahoma for Oral Health PAC",
            "position": "FOR",
            "amount": 450,
            "currency": "USD",
            "description": "PAC contribution to Adam Pugh's candidate committee on 01/14/2026 (reported as PAC expenditure)",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ExpenditureExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission (Guardian System)"
          },
          {
            "pacName": "Oklahoma Academy of Physician Associates",
            "position": "FOR",
            "amount": 1000,
            "currency": "USD",
            "description": "PAC contribution to Adam Pugh's candidate committee on 01/16/2026 (reported as PAC expenditure)",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ExpenditureExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission (Guardian System)"
          },
          {
            "pacName": "American Farmers & Ranchers/Oklahoma State Union of the Farmers Education & Cooperative Union of America, Inc.",
            "position": "FOR",
            "amount": 500,
            "currency": "USD",
            "description": "PAC contribution to Adam Pugh's candidate committee on 01/26/2026 (reported as PAC expenditure)",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ExpenditureExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission (Guardian System)"
          },
          {
            "pacName": "Thoroughbred PAC",
            "position": "FOR",
            "amount": 400,
            "currency": "USD",
            "description": "PAC contribution to Adam Pugh's candidate committee on 04/08/2026",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission (Guardian System)"
          }
        ]
      },
      {
        "name": "DEBRA A. HERLIHY",
        "pacSpending": []
      },
      {
        "name": "WILLIAM E CROZIER",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-superintendent-of-public-instruction-democrat",
    "raceTitle": "FOR SUPERINTENDENT OF PUBLIC INSTRUCTION",
    "party": "DEMOCRAT",
    "candidates": [
      {
        "name": "JENNETTIE MARSHALL",
        "pacSpending": []
      },
      {
        "name": "CRAIG MCVAY",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-attorney-general-republican",
    "raceTitle": "FOR ATTORNEY GENERAL",
    "party": "REPUBLICAN",
    "candidates": [
      {
        "name": "JON ECHOLS",
        "pacSpending": [
          {
            "pacName": "Secure Oklahoma PAC",
            "position": "AGAINST",
            "amount": 3420000,
            "currency": "USD",
            "description": "Independent expenditures on advertising opposing Jon Echols in the Republican attorney general primary; the same $3.42 million campaign also supports Jeff Starling. Reported to the Oklahoma Ethics Commission.",
            "sourceUrl": "https://oklahomawatch.org/2026/06/15/republican-primaries-for-governor-attorney-general-drive-record-outside-spending/",
            "sourceName": "Oklahoma Watch / Oklahoma Ethics Commission"
          }
        ]
      },
      {
        "name": "JEFF STARLING",
        "pacSpending": [
          {
            "pacName": "Secure Oklahoma PAC",
            "position": "FOR",
            "amount": 3420000,
            "currency": "USD",
            "description": "Independent expenditures on advertising supporting Jeff Starling in the Republican attorney general primary; the same $3.42 million campaign also opposes Jon Echols. Reported to the Oklahoma Ethics Commission.",
            "sourceUrl": "https://oklahomawatch.org/2026/06/15/republican-primaries-for-governor-attorney-general-drive-record-outside-spending/",
            "sourceName": "Oklahoma Watch / Oklahoma Ethics Commission"
          },
          {
            "pacName": "Electing a Conservative and Honest Oklahoman PAC",
            "position": "AGAINST",
            "amount": 2726061.18,
            "currency": "USD",
            "description": "Negative advertising against Jeff Starling in the Republican attorney general primary, funded by the dark-money group Conservative Agenda for America. Amount is the PAC's total 2026 independent expenditures reported to the Oklahoma Ethics Commission through June 9, 2026.",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission Guardian"
          }
        ]
      }
    ]
  },
  {
    "raceId": "for-state-treasurer-republican",
    "raceTitle": "FOR STATE TREASURER",
    "party": "REPUBLICAN",
    "candidates": [
      {
        "name": "TODD RUSS",
        "pacSpending": [
          {
            "pacName": "NEXTERA ENERGY PAC",
            "position": "FOR",
            "amount": 1500,
            "currency": "USD",
            "description": "PAC contribution to Todd Russ for State Treasurer 2026 committee on 02/28/2025",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2025_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission - Guardian Bulk Data Download"
          },
          {
            "pacName": "CONTINENTAL RESOURCES PAC",
            "position": "FOR",
            "amount": 2500,
            "currency": "USD",
            "description": "PAC contribution to Todd Russ for State Treasurer 2026 committee on 03/22/2025",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2025_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission - Guardian Bulk Data Download"
          },
          {
            "pacName": "UNITED COMMUNITY BANKER POLITICAL ACTION COMMITTEE",
            "position": "FOR",
            "amount": 2500,
            "currency": "USD",
            "description": "PAC contribution to Todd Russ for State Treasurer 2026 committee on 09/04/2025",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2025_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission - Guardian Bulk Data Download"
          },
          {
            "pacName": "COX COMMUNICATIONS OKLAHOMA PAC FUND",
            "position": "FOR",
            "amount": 1000,
            "currency": "USD",
            "description": "PAC contribution to Todd Russ for State Treasurer 2026 committee on 12/22/2025",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2025_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission - Guardian Bulk Data Download"
          },
          {
            "pacName": "TURNAROUND TEAM PAC",
            "position": "FOR",
            "amount": 5000,
            "currency": "USD",
            "description": "PAC contribution to Todd Russ for State Treasurer 2026 committee on 04/22/2026",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission - Guardian Bulk Data Download"
          },
          {
            "pacName": "OKLAHOMA BANKERS PUBLIC AFFAIRS COMMITTEE",
            "position": "FOR",
            "amount": 1000,
            "currency": "USD",
            "description": "PAC contribution to Todd Russ for State Treasurer 2026 committee on 05/11/2026",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission - Guardian Bulk Data Download"
          },
          {
            "pacName": "CONTINENTAL RESOURCES PAC",
            "position": "FOR",
            "amount": 2500,
            "currency": "USD",
            "description": "PAC contribution to Todd Russ for State Treasurer 2026 committee on 05/16/2026",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission - Guardian Bulk Data Download"
          },
          {
            "pacName": "PETROLEUM ALLIANCE PAC",
            "position": "FOR",
            "amount": 2500,
            "currency": "USD",
            "description": "PAC contribution to Todd Russ for State Treasurer 2026 committee on 05/16/2026",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission - Guardian Bulk Data Download"
          },
          {
            "pacName": "AMERICAN FIDELITY CORPORATION PAC",
            "position": "FOR",
            "amount": 2000,
            "currency": "USD",
            "description": "PAC contribution to Todd Russ for State Treasurer 2026 committee on 05/21/2026",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission - Guardian Bulk Data Download"
          },
          {
            "pacName": "OKLAHOMA TITLE POLITICAL ACTION COMMITTEE",
            "position": "FOR",
            "amount": 5000,
            "currency": "USD",
            "description": "PAC contribution to Todd Russ for State Treasurer 2026 committee on 05/30/2026",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission - Guardian Bulk Data Download"
          },
          {
            "pacName": "COMMUNITY BANKERS ASSOCIATION OF OKLAHOMA",
            "position": "FOR",
            "amount": 2500,
            "currency": "USD",
            "description": "PAC contribution to Todd Russ for State Treasurer 2026 committee on 06/09/2026",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission - Guardian Bulk Data Download"
          }
        ]
      },
      {
        "name": "CINDY BYRD",
        "pacSpending": [
          {
            "pacName": "OKLAHOMA CITY FIREFIGHTERS ASSOCIATION",
            "position": "FOR",
            "amount": 2500,
            "currency": "USD",
            "description": "PAC contribution to Cindy Byrd for State Treasurer 2026 committee on 05/29/2026",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/Docs/BulkDataDownloads/2026_ContributionLoanExtract.csv.zip",
            "sourceName": "Oklahoma Ethics Commission - Guardian Bulk Data Download"
          }
        ]
      }
    ]
  },
  {
    "raceId": "for-lieutenant-governor-republican",
    "raceTitle": "FOR LIEUTENANT GOVERNOR",
    "party": "REPUBLICAN",
    "candidates": [
      {
        "name": "H. VICTOR FLORES",
        "pacSpending": []
      },
      {
        "name": "T. W. SHANNON",
        "pacSpending": [
          {
            "pacName": "Oklahoma Association of General Contractors PAC",
            "position": "FOR",
            "amount": 5000,
            "currency": "USD",
            "description": "PAC contribution to T. W. Shannon's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Affiliated Anesthesiologists PAC",
            "position": "FOR",
            "amount": 5000,
            "currency": "USD",
            "description": "PAC contribution to T. W. Shannon's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "American Fidelity Corporation Political Action Committee",
            "position": "FOR",
            "amount": 2500,
            "currency": "USD",
            "description": "PAC contribution to T. W. Shannon's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Homebuilders PAC",
            "position": "FOR",
            "amount": 2500,
            "currency": "USD",
            "description": "PAC contribution to T. W. Shannon's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma Bankers Public Affairs Committee",
            "position": "FOR",
            "amount": 2000,
            "currency": "USD",
            "description": "PAC contribution to T. W. Shannon's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "CARE PAC",
            "position": "FOR",
            "amount": 1500,
            "currency": "USD",
            "description": "PAC contribution to T. W. Shannon's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Association of Oklahoma Nurse Practitioners",
            "position": "FOR",
            "amount": 1500,
            "currency": "USD",
            "description": "PAC contribution to T. W. Shannon's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma Association of Nurse Anesthetist Political Action Committee",
            "position": "FOR",
            "amount": 1500,
            "currency": "USD",
            "description": "PAC contribution to T. W. Shannon's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Bondsman Political Action Committee",
            "position": "FOR",
            "amount": 1000,
            "currency": "USD",
            "description": "PAC contribution to T. W. Shannon's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Continental Resources, Inc. Political Action Committee",
            "position": "FOR",
            "amount": 1000,
            "currency": "USD",
            "description": "PAC contribution to T. W. Shannon's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma Optometric Political Action Committee",
            "position": "FOR",
            "amount": 500,
            "currency": "USD",
            "description": "PAC contribution to T. W. Shannon's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "GarverUSA PAC",
            "position": "FOR",
            "amount": 500,
            "currency": "USD",
            "description": "PAC contribution to T. W. Shannon's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma Prosperity Fund, LLC",
            "position": "FOR",
            "amount": 1070560,
            "currency": "USD",
            "description": "Independent expenditure supporting T. W. Shannon",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/SearchPages/Search.aspx?SearchTypeCodeHook=3FF86095-94E1-4145-A34F-248A7C4B4540",
            "sourceName": "Oklahoma Ethics Commission"
          }
        ]
      },
      {
        "name": "DARRELL WEAVER",
        "pacSpending": [
          {
            "pacName": "FOP 123 PAC Fund",
            "position": "FOR",
            "amount": 5000,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma Fraternal Order of Police State Lodge PAC",
            "position": "FOR",
            "amount": 5000,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "OKC Firefighters Association PAC Fund",
            "position": "FOR",
            "amount": 5000,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "QuikTrip Corporation Political Action Committee",
            "position": "FOR",
            "amount": 4300,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma Fire Political Action Committee",
            "position": "FOR",
            "amount": 2500,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Tulsa Firefighters PAC",
            "position": "FOR",
            "amount": 2500,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Tulsa Fraternal Order of Police 93 PAC",
            "position": "FOR",
            "amount": 2500,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma Optometric Political Action Committee",
            "position": "FOR",
            "amount": 1500,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma Bankers Public Affairs Committee",
            "position": "FOR",
            "amount": 1000,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma City Retired Firefighters Association PAC",
            "position": "FOR",
            "amount": 1000,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Beer Distributors of Oklahoma Political Action Committee",
            "position": "FOR",
            "amount": 500,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma Dental PAC",
            "position": "FOR",
            "amount": 500,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Motorola Solutions PAC",
            "position": "FOR",
            "amount": 500,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "American Fidelity Corp PAC",
            "position": "FOR",
            "amount": 500,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Cornerstone Government Affairs Oklahoma PAC",
            "position": "FOR",
            "amount": 500,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma Pharmacists Association PAC",
            "position": "FOR",
            "amount": 500,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Delta Dental of Oklahoma for Oral Health PAC",
            "position": "FOR",
            "amount": 450,
            "currency": "USD",
            "description": "PAC contribution to Darrell Weaver's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma State Medical Association",
            "position": "FOR",
            "amount": 50000,
            "currency": "USD",
            "description": "Independent expenditure supporting Darrell Weaver (itemized portion of larger multi-candidate buy)",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/SearchPages/Search.aspx?SearchTypeCodeHook=3FF86095-94E1-4145-A34F-248A7C4B4540",
            "sourceName": "Oklahoma Ethics Commission"
          }
        ]
      },
      {
        "name": "DAVID OSTROWE",
        "pacSpending": [
          {
            "pacName": "46 Action",
            "position": "FOR",
            "amount": 15000,
            "currency": "USD",
            "description": "Independent expenditure supporting David Ostrowe",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/SearchPages/Search.aspx?SearchTypeCodeHook=3FF86095-94E1-4145-A34F-248A7C4B4540",
            "sourceName": "Oklahoma Ethics Commission"
          }
        ]
      },
      {
        "name": "JUSTIN JJ HUMPHREY",
        "pacSpending": []
      },
      {
        "name": "BRIAN HILL",
        "pacSpending": [
          {
            "pacName": "Health Care Service Corporation Employees' PAC",
            "position": "FOR",
            "amount": 750,
            "currency": "USD",
            "description": "PAC contribution to Brian Hill's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma Bankers Public Affairs Committee",
            "position": "FOR",
            "amount": 500,
            "currency": "USD",
            "description": "PAC contribution to Brian Hill's candidate committee",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/DataDownload.aspx",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "Oklahoma First PAC",
            "position": "FOR",
            "amount": 47500,
            "currency": "USD",
            "description": "Independent expenditure supporting Brian Hill",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/SearchPages/Search.aspx?SearchTypeCodeHook=3FF86095-94E1-4145-A34F-248A7C4B4540",
            "sourceName": "Oklahoma Ethics Commission"
          }
        ]
      }
    ]
  },
  {
    "raceId": "for-commissioner-of-labor-republican",
    "raceTitle": "FOR COMMISSIONER OF LABOR",
    "party": "REPUBLICAN",
    "candidates": [
      {
        "name": "JOHN PFEIFFER",
        "pacSpending": []
      },
      {
        "name": "LISA JANLOO",
        "pacSpending": []
      },
      {
        "name": "KEITH SWINTON",
        "pacSpending": []
      },
      {
        "name": "KEVIN WEST",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-insurance-commissioner-republican",
    "raceTitle": "FOR INSURANCE COMMISSIONER",
    "party": "REPUBLICAN",
    "candidates": [
      {
        "name": "CHRIS MERIDETH",
        "pacSpending": []
      },
      {
        "name": "GRETA SHULER",
        "pacSpending": []
      },
      {
        "name": "MARTY L QUINN",
        "pacSpending": [
          {
            "pacName": "DEFEND US PAC",
            "position": "FOR",
            "amount": 15000,
            "currency": "USD",
            "description": "Independent expenditure for radio advertising (Public IE EC SQ Report - 2ND QUARTER, 06/14/2026 - 06/15/2026; filed 6/15/2026)",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/SearchPages/Search.aspx?SearchTypeCodeHook=3FF86095-94E1-4145-A34F-248A7C4B4540",
            "sourceName": "Oklahoma Ethics Commission"
          }
        ]
      },
      {
        "name": "BOB SULLIVAN",
        "pacSpending": [
          {
            "pacName": "OKLAHOMA STATE MEDICAL ASSOCIATION",
            "position": "FOR",
            "amount": 8500,
            "currency": "USD",
            "description": "Independent expenditure for video services (Public IE EC SQ Report - 1ST QUARTER, 1/1/2026 - 3/31/2026; filed 4/27/2026)",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/SearchPages/Search.aspx?SearchTypeCodeHook=3FF86095-94E1-4145-A34F-248A7C4B4540",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "OKLAHOMA STATE MEDICAL ASSOCIATION",
            "position": "FOR",
            "amount": 75000,
            "currency": "USD",
            "description": "Independent expenditure for advertising media buy (Public IE EC SQ Report - 1ST QUARTER, 1/1/2026 - 3/31/2026; filed 4/27/2026)",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/SearchPages/Search.aspx?SearchTypeCodeHook=3FF86095-94E1-4145-A34F-248A7C4B4540",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "OKLAHOMA STATE MEDICAL ASSOCIATION",
            "position": "FOR",
            "amount": 146500,
            "currency": "USD",
            "description": "Independent expenditure for ad creation and digital ad buy (Public IE EC SQ Report - PRE-ELECTION, 4/1/2026 - 6/1/2026; filed 6/8/2026)",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/SearchPages/Search.aspx?SearchTypeCodeHook=3FF86095-94E1-4145-A34F-248A7C4B4540",
            "sourceName": "Oklahoma Ethics Commission"
          }
        ]
      }
    ]
  },
  {
    "raceId": "for-corporation-commissioner-democrat",
    "raceTitle": "FOR CORPORATION COMMISSIONER",
    "party": "DEMOCRAT",
    "candidates": [
      {
        "name": "DONALD ANTHONY CLYTUS",
        "pacSpending": []
      },
      {
        "name": "RHONDA EASTMAN",
        "pacSpending": []
      },
      {
        "name": "HAROLD D. SPRADLING",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-corporation-commissioner-republican",
    "raceTitle": "FOR CORPORATION COMMISSIONER",
    "party": "REPUBLICAN",
    "candidates": [
      {
        "name": "BRAD BOLES",
        "pacSpending": [
          {
            "pacName": "AMERICAN ENERGY ACTION",
            "position": "FOR",
            "amount": 50000,
            "currency": "USD",
            "description": "Independent expenditure for digital advocacy advertising/streaming audio/text messages/telephone calls for Brad Boles (Corporation Commissioner), paid to Advocacy Architects, LLC, filed 6/2/2026",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/SearchPages/Search.aspx?SearchTypeCodeHook=3FF86095-94E1-4145-A34F-248A7C4B4540",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "OKLAHOMA CONSERVATIVE COALITION",
            "position": "FOR",
            "amount": 73750,
            "currency": "USD",
            "description": "Independent expenditures for Brad Boles (Corporation Commissioner): radio advertisement ($30,000) filed 6/10/2026 (amended), canvassing ($28,750) and radio advertisement ($15,000) filed 6/9/2026",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/SearchPages/Search.aspx?SearchTypeCodeHook=3FF86095-94E1-4145-A34F-248A7C4B4540",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "OKLAHOMA FARM BUREAU",
            "position": "FOR",
            "amount": 2400,
            "currency": "USD",
            "description": "Independent expenditures for social media ads for Brad Boles (Corporation Commissioner), filed 6/8/2026",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/SearchPages/Search.aspx?SearchTypeCodeHook=3FF86095-94E1-4145-A34F-248A7C4B4540",
            "sourceName": "Oklahoma Ethics Commission"
          },
          {
            "pacName": "OKLAHOMA JOBS FIRST FUND, LLC",
            "position": "FOR",
            "amount": 90045,
            "currency": "USD",
            "description": "Independent expenditure for direct mail for Brad Boles (Corporation Commissioner), paid to South Creek Group, filed 6/7/2026",
            "sourceUrl": "https://guardian.ok.gov/PublicSite/SearchPages/Search.aspx?SearchTypeCodeHook=3FF86095-94E1-4145-A34F-248A7C4B4540",
            "sourceName": "Oklahoma Ethics Commission"
          }
        ]
      },
      {
        "name": "JUSTIN HORNBACK",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-united-states-representative-district-02-democrat",
    "raceTitle": "FOR UNITED STATES REPRESENTATIVE",
    "subtitle": "DISTRICT 02",
    "party": "DEMOCRAT",
    "candidates": [
      {
        "name": "ERIK TERWEY",
        "pacSpending": []
      },
      {
        "name": "BRANDON WADE",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-united-states-representative-district-02-republican",
    "raceTitle": "FOR UNITED STATES REPRESENTATIVE",
    "subtitle": "DISTRICT 02",
    "party": "REPUBLICAN",
    "candidates": [
      {
        "name": "JOSH BRECHEEN",
        "pacSpending": [
          {
            "pacName": "FREEDOM CAUCUS FUND",
            "position": "FOR",
            "amount": 266.21,
            "currency": "USD",
            "description": "IE- BRECHEEN - DONATION PROCESSING",
            "sourceUrl": "https://www.fec.gov/data/independent-expenditures/?candidate_id=H2OK02315&cycle=2026",
            "sourceName": "FEC"
          }
        ]
      },
      {
        "name": "WILL WEBB",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-united-states-representative-district-03-democrat",
    "raceTitle": "FOR UNITED STATES REPRESENTATIVE",
    "subtitle": "DISTRICT 03",
    "party": "DEMOCRAT",
    "candidates": [
      {
        "name": "SUZIE BYRD",
        "pacSpending": []
      },
      {
        "name": "JULES ROBERSON",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-united-states-representative-district-03-republican",
    "raceTitle": "FOR UNITED STATES REPRESENTATIVE",
    "subtitle": "DISTRICT 03",
    "party": "REPUBLICAN",
    "candidates": [
      {
        "name": "FRANK D. LUCAS",
        "pacSpending": []
      },
      {
        "name": "WADE BURLESON",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-united-states-representative-district-04-democrat",
    "raceTitle": "FOR UNITED STATES REPRESENTATIVE",
    "subtitle": "DISTRICT 04",
    "party": "DEMOCRAT",
    "candidates": [
      {
        "name": "JEFF PIXLEY",
        "pacSpending": []
      },
      {
        "name": "MITCHELL JACOB",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-united-states-representative-district-04-republican",
    "raceTitle": "FOR UNITED STATES REPRESENTATIVE",
    "subtitle": "DISTRICT 04",
    "party": "REPUBLICAN",
    "candidates": [
      {
        "name": "MARCIE EVERHART",
        "pacSpending": []
      },
      {
        "name": "TOM COLE",
        "pacSpending": [
          {
            "pacName": "AMERICANS 4 SECURITY PAC",
            "position": "FOR",
            "amount": 500000,
            "currency": "USD",
            "description": "MEDIA SPEND: BROADCAST, FOXCABLE AND DIGITAL OTT",
            "sourceUrl": "https://www.fec.gov/data/independent-expenditures/?candidate_id=H2OK04055&cycle=2026",
            "sourceName": "FEC"
          }
        ]
      }
    ]
  },
  {
    "raceId": "for-united-states-representative-district-05-democrat",
    "raceTitle": "FOR UNITED STATES REPRESENTATIVE",
    "subtitle": "DISTRICT 05",
    "party": "DEMOCRAT",
    "candidates": [
      {
        "name": "TREY MARTIN",
        "pacSpending": [
          {
            "pacName": "LEAGUE OF LABOR VOTERS",
            "position": "FOR",
            "amount": 584914.56,
            "currency": "USD",
            "description": "7 independent expenditure transactions",
            "sourceUrl": "https://www.fec.gov/data/independent-expenditures/?candidate_id=H6OK05319&cycle=2026",
            "sourceName": "FEC"
          }
        ]
      },
      {
        "name": "JENA NELSON",
        "pacSpending": []
      }
    ]
  },
  {
    "raceId": "for-united-states-representative-district-01-republican",
    "raceTitle": "FOR UNITED STATES REPRESENTATIVE",
    "subtitle": "DISTRICT 01",
    "party": "REPUBLICAN",
    "candidates": [
      {
        "name": "TODD WOODS",
        "pacSpending": []
      },
      {
        "name": "NANCY DYSON",
        "pacSpending": []
      },
      {
        "name": "PAUL ROYSE",
        "pacSpending": []
      },
      {
        "name": "COURTNEY GILL",
        "pacSpending": []
      },
      {
        "name": "JACKSON LAHMEYER",
        "pacSpending": [
          {
            "pacName": "CLUB FOR GROWTH ACTION",
            "position": "FOR",
            "amount": 478721.85,
            "currency": "USD",
            "description": "12 independent expenditure transactions",
            "sourceUrl": "https://www.fec.gov/data/independent-expenditures/?candidate_id=H6OK01284&cycle=2026",
            "sourceName": "FEC"
          }
        ]
      },
      {
        "name": "MARK TEDFORD",
        "pacSpending": [
          {
            "pacName": "HEARTLAND VICTORY PAC",
            "position": "FOR",
            "amount": 95000,
            "currency": "USD",
            "description": "DIGITAL PLACEMENT AND PRODUCTION; DIRECT MAIL",
            "sourceUrl": "https://www.fec.gov/data/independent-expenditures/?candidate_id=H6OK01235&cycle=2026",
            "sourceName": "FEC"
          }
        ]
      },
      {
        "name": "KIM DAVID",
        "pacSpending": [
          {
            "pacName": "GOPAC ELECTION FUND",
            "position": "FOR",
            "amount": 14000,
            "currency": "USD",
            "description": "PRINTING/CANVASSING",
            "sourceUrl": "https://www.fec.gov/data/independent-expenditures/?candidate_id=H6OK01250&cycle=2026",
            "sourceName": "FEC"
          }
        ]
      },
      {
        "name": "JED COCHRAN",
        "pacSpending": []
      },
      {
        "name": "KELLY B. WALSH",
        "pacSpending": []
      },
      {
        "name": "DAN ROONEY",
        "pacSpending": []
      },
      {
        "name": "NATHAN BUTTERFIELD",
        "pacSpending": [
          {
            "pacName": "SOONER INTEGRITY FUND",
            "position": "AGAINST",
            "amount": 7000,
            "currency": "USD",
            "description": "Video production and Internet advertising",
            "sourceUrl": "https://www.fec.gov/data/independent-expenditures/?candidate_id=H6OK01276&cycle=2026",
            "sourceName": "FEC"
          }
        ]
      }
    ]
  }
]
